# Generated by Django 5.1.3 on 2024-11-24 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_credential_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShippingDetails',
            fields=[
                ('first_name', models.CharField(validators=[django.core.validators.RegexValidator(message='This field requires $2-$255 letters', regex='^[A-Za-z]{2,255}$')])),
                ('last_name', models.CharField()),
                ('phone_number', models.CharField()),
                ('country', models.CharField()),
                ('city', models.CharField()),
                ('street', models.CharField()),
                ('apartment', models.CharField()),
                ('postal_code', models.CharField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shipping_details', serialize=False, to='user_credential_details.usercredentialdetails')),
            ],
        ),
    ]
