# Generated by Django 5.1.3 on 2024-11-24 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0011_alter_usershippingdetails_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingdetails',
            name='first_name',
            field=models.CharField(default='bea', validators=[django.core.validators.RegexValidator(message='Please make sure your First Name contains only letters', regex='^[A-Za-z]$'), django.core.validators.MinLengthValidator(2, message='First name must be at least 2 characters long'), django.core.validators.MaxLengthValidator(255, message=('First name cannot be longer than 255 characters',))]),
            preserve_default=False,
        ),
    ]
