# Generated by Django 5.1.3 on 2024-11-24 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0013_alter_usershippingdetails_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingdetails',
            name='first_name',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Please make sure your First Name contains only letters', regex='[A-Za-z]'), django.core.validators.MinLengthValidator(2, message='First name must be at least 2 characters long'), django.core.validators.MaxLengthValidator(255, message=('First name cannot be longer than 255 characters',))]),
        ),
    ]
