# Generated by Django 5.1.3 on 2024-11-25 12:08

import django.core.validators
import django_ecommerce_strategy_pattern.user_shipping_details.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0017_alter_usershippingdetails_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingdetails',
            name='first_name',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Please make sure your First Name contains only letters', regex='^[A-Za-z]+$'), django_ecommerce_strategy_pattern.user_shipping_details.validators.Validator(error_message='please enter your first name', length_limit=0, method=django_ecommerce_strategy_pattern.user_shipping_details.validators.ValidationMethod['ZERO_LENGTH']), django_ecommerce_strategy_pattern.user_shipping_details.validators.Validator(error_message='First Name must be at least 2 characters long', length_limit=2, method=django_ecommerce_strategy_pattern.user_shipping_details.validators.ValidationMethod['MIN_LENGTH']), django.core.validators.MinLengthValidator(limit_value=2, message='First Name must be at least 2 characters long'), django.core.validators.MaxLengthValidator(limit_value=255, message=('First Name cannot be longer than 255 characters',))]),
        ),
    ]
