# Generated by Django 5.1.3 on 2024-11-26 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0021_alter_usershippingdetails_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingdetails',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'Please enter your First Name', 'max_length': ('First Name cannot be longer than 5 characters',)}, max_length=5, validators=[django.core.validators.RegexValidator(message='Please make sure your First Name contains only letters', regex='^[A-Za-z]+$'), django.core.validators.MinLengthValidator(limit_value=2, message='First Name must be at least 2 characters long')]),
        ),
    ]
