# Generated by Django 5.1.3 on 2024-11-26 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0023_remove_usershippingdetails_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingdetails',
            name='apartment',
            field=models.CharField(blank=True, error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 10 characters'}, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='This field must be at least 1 characters long'), django.core.validators.RegexValidator(message='This field can only contain letters, spaces, hyphens, and periods, and must start and end with a letter or digit', regex='^([A-Za-z0-9]{1,5})([A-Za-z0-9\\s\\-\\.]{0,4})([A-Za-z0-9]?)$')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='city',
            field=models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='This field must be at least 2 characters long'), django.core.validators.RegexValidator(message='City Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{2,}$)|(^[A-Za-z]{1,}[\\s\\-]?[A-Za-z]{1,}$)')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='country',
            field=models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='This field must be at least 2 characters long'), django.core.validators.RegexValidator(message='Country Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{2,}$)|(^[A-Za-z]{1,}[\\s\\-]?[A-Za-z]{1,}$)')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='This field must be at least 2 characters long'), django.core.validators.RegexValidator(message='First Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{2,}$)|(^[A-Za-z]{1,}[\\s\\-]?[A-Za-z]{1,}$)')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='This field must be at least 2 characters long'), django.core.validators.RegexValidator(message='Last Name can only contain letters, spaces, hyphens, and must start and end with a letter', regex='(^[A-Za-z]{2,}$)|(^[A-Za-z]{1,}[\\s\\-]?[A-Za-z]{1,}$)')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='phone_number',
            field=models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 15 characters'}, max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=7, message='This field must be at least 7 characters long'), django.core.validators.RegexValidator(message='This field can only contain digits', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='postal_code',
            field=models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 15 characters'}, max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='This field must be at least 3 characters long'), django.core.validators.RegexValidator(message='This field can only contain letters, spaces, hyphens, commas, and periods, and must start and end with a letter or digit', regex='^([A-Za-z0-9]{2})([A-Za-z0-9\\s\\-\\.\\,]{0,12})([A-Za-z0-9]{1})$')]),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='street_address',
            field=models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 255 characters'}, max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='This field must be at least 8 characters long'), django.core.validators.RegexValidator(message='This field can only contain letters, spaces, hyphens, apostrophes, and periods, and must start and end with a letter or digit', regex="^([A-Za-z0-9]{1,})([A-Za-z0-9\\s\\-\\.']{6,})([A-Za-z0-9])$")]),
        ),
    ]
