# Generated by Django 4.2 on 2024-01-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='size',
            field=models.CharField(default='mmmmmm', max_length=10),
            preserve_default=False,
        ),
    ]
