# Generated by Django 5.0 on 2024-01-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='session_key',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
