# Generated by Django 5.0 on 2024-01-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
        ('shopping_cart', '0005_shoppingcart_session_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('session_key', 'jewelry')},
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
    ]
