# Generated by Django 5.2 on 2025-04-27 07:18

import django.core.validators
import travelers_hub.travelers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='*Nicknames can contain only letters and digits.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), travelers_hub.travelers.validators.AlphaNumericValidator()])),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('country', models.CharField(validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
