# Generated by Django 5.2 on 2025-04-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='ddd', upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
