# Generated by Django 5.1.3 on 2024-11-23 15:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('ES', 4.05), ('EM', 4.98), ('EL', 5.86), ('BS', 15.02), ('BM', 17.08), ('BL', 19.03), ('NS', 40.64), ('NM', 43.18), ('NL', 45.72), ('RS', 4.07), ('RM', 4.09), ('RL', 5.05)], max_length=2, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('ES', 43000.0), ('EM', 44000.0), ('EL', 45000.0), ('BS', 34000.0), ('BM', 35000.0), ('BL', 36000.0), ('NS', 55000.0), ('NM', 56000.0), ('NL', 57000.0), ('RS', 23000.0), ('RM', 24000.0), ('RL', 25000.0)], max_length=2, unique=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='inventory.size')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3, message='The maximum quantity per product inventory is 3.')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='product.product')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_inventory', to='inventory.price')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_inventory', to='inventory.size')),
            ],
            options={
                'unique_together': {('product', 'size', 'price')},
            },
        ),
    ]
