# Generated by Django 5.1.3 on 2024-11-23 12:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3, message='The maximum quantity per product inventory is 3.')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'size', 'price')},
            },
        ),
    ]
