# Generated by Django 5.1.3 on 2024-11-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_credential_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentDetails',
            fields=[
                ('card_holder', models.CharField()),
                ('card_number', models.CharField()),
                ('expiry_date', models.DateField()),
                ('cvv_code', models.CharField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_details', serialize=False, to='user_credential_details.usercredentialdetails')),
            ],
        ),
    ]
