# Generated by Django 5.1.3 on 2024-11-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentdetails',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
