# Generated by Django 5.1.3 on 2024-11-25 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment_details', '0003_alter_userpaymentdetails_card_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentdetails',
            name='card_number',
            field=models.CharField(error_messages={'blank': 'Please enter a valid Card Number'}, validators=[django.core.validators.RegexValidator(message='Please make sure your Card Number contains only digits', regex='^\\d+$'), django.core.validators.MinLengthValidator(limit_value=16, message='Card Number must be exactly 16 digits long'), django.core.validators.MaxLengthValidator(limit_value=16, message='Card Number must be exactly 16 digits long')]),
        ),
    ]
