# Generated by Django 5.2 on 2025-04-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('PM', 'Pop Music'), ('JM', 'Jazz Music'), ('RBM', 'R&B Music'), ('RM', 'Rock Music'), ('CM', 'Country Music'), ('DM', 'Dance Music'), ('HHM', 'Hip Hop Music'), ('OT', 'Other')], max_length=30),
        ),
    ]
