const url =
  "https://api.thecatapi.com/v1/images/search?limit=10&has_breeds=1&api_key=live_tsajPiuraUElbMg02ZXoB0xjlNtutoamS75kWTdQKYQ3pHWnaWAuRjw8MRcX98oD&breed_ids=acur&breed_ids=pers&breed_ids=bslo&breed_ids=birm&breed_ids=sfol&breed_ids=ragd&breed_ids=tang";

// function catContext() {
//   const cats = [
//     {
//       breeds: [
//         {
//           weight: { imperial: "8 - 18", metric: "4 - 8" },
//           id: "bslo",
//           name: "British Longhair",
//           temperament:
//             "Affectionate, Easy Going, Independent, Intelligent, Loyal, Social",
//           origin: "United Kingdom",
//           country_codes: "GB",
//           country_code: "GB",
//           description:
//             "The British Longhair is a very laid-back relaxed cat, often perceived to be very independent although they will enjoy the company of an equally relaxed and likeminded cat. They are an affectionate breed, but very much on their own terms and tend to prefer to choose to come and sit with their owners rather than being picked up.",
//           life_span: "12 - 14",
//           indoor: 0,
//           alt_names: "",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 4,
//           grooming: 5,
//           health_issues: 1,
//           intelligence: 5,
//           shedding_level: 1,
//           social_needs: 3,
//           stranger_friendly: 4,
//           vocalisation: 1,
//           experimental: 0,
//           hairless: 0,
//           natural: 0,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/British_Longhair",
//           hypoallergenic: 0,
//           reference_image_id: "7isAO4Cav",
//         },
//       ],
//       id: "JWOrjbhum",
//       url: "https://cdn2.thecatapi.com/images/JWOrjbhum.jpg",
//       width: 768,
//       height: 1024,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "9 - 14", metric: "4 - 6" },
//           id: "pers",
//           name: "Persian",
//           cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Persian.aspx",
//           vetstreet_url: "http://www.vetstreet.com/cats/persian",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/persian",
//           temperament: "Affectionate, loyal, Sedate, Quiet",
//           origin: "Iran (Persia)",
//           country_codes: "IR",
//           country_code: "IR",
//           description:
//             "Persians are sweet, gentle cats that can be playful or quiet and laid-back. Great with families and children, they absolutely love to lounge around the house. While they don’t mind a full house or active kids, they’ll usually hide when they need some alone time.",
//           life_span: "14 - 15",
//           indoor: 0,
//           lap: 1,
//           alt_names: "Longhair, Persian Longhair, Shiraz, Shirazi",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 2,
//           dog_friendly: 2,
//           energy_level: 1,
//           grooming: 5,
//           health_issues: 3,
//           intelligence: 3,
//           shedding_level: 4,
//           social_needs: 4,
//           stranger_friendly: 2,
//           vocalisation: 1,
//           experimental: 0,
//           hairless: 0,
//           natural: 1,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Persian_(cat)",
//           hypoallergenic: 0,
//           reference_image_id: "-Zfz5z2jK",
//         },
//       ],
//       id: "tSbM4vHB_",
//       url: "https://cdn2.thecatapi.com/images/tSbM4vHB_.png",
//       width: 4096,
//       height: 2304,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "12 - 20", metric: "5 - 9" },
//           id: "ragd",
//           name: "Ragdoll",
//           cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Ragdoll.aspx",
//           vetstreet_url: "http://www.vetstreet.com/cats/ragdoll",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/ragdoll",
//           temperament: "Affectionate, Friendly, Gentle, Quiet, Easygoing",
//           origin: "United States",
//           country_codes: "US",
//           country_code: "US",
//           description:
//             "Ragdolls love their people, greeting them at the door, following them around the house, and leaping into a lap or snuggling in bed whenever given the chance. They are the epitome of a lap cat, enjoy being carried and collapsing into the arms of anyone who holds them.",
//           life_span: "12 - 17",
//           indoor: 0,
//           lap: 1,
//           alt_names: "Rag doll",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 3,
//           grooming: 2,
//           health_issues: 3,
//           intelligence: 3,
//           shedding_level: 3,
//           social_needs: 5,
//           stranger_friendly: 3,
//           vocalisation: 1,
//           experimental: 0,
//           hairless: 0,
//           natural: 0,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Ragdoll",
//           hypoallergenic: 0,
//           reference_image_id: "oGefY4YoG",
//         },
//       ],
//       id: "UYLI_E-SZ",
//       url: "https://cdn2.thecatapi.com/images/UYLI_E-SZ.jpg",
//       width: 750,
//       height: 500,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "12 - 20", metric: "5 - 9" },
//           id: "ragd",
//           name: "Ragdoll",
//           cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Ragdoll.aspx",
//           vetstreet_url: "http://www.vetstreet.com/cats/ragdoll",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/ragdoll",
//           temperament: "Affectionate, Friendly, Gentle, Quiet, Easygoing",
//           origin: "United States",
//           country_codes: "US",
//           country_code: "US",
//           description:
//             "Ragdolls love their people, greeting them at the door, following them around the house, and leaping into a lap or snuggling in bed whenever given the chance. They are the epitome of a lap cat, enjoy being carried and collapsing into the arms of anyone who holds them.",
//           life_span: "12 - 17",
//           indoor: 0,
//           lap: 1,
//           alt_names: "Rag doll",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 3,
//           grooming: 2,
//           health_issues: 3,
//           intelligence: 3,
//           shedding_level: 3,
//           social_needs: 5,
//           stranger_friendly: 3,
//           vocalisation: 1,
//           experimental: 0,
//           hairless: 0,
//           natural: 0,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Ragdoll",
//           hypoallergenic: 0,
//           reference_image_id: "oGefY4YoG",
//         },
//       ],
//       id: "TnwHiS7nO",
//       url: "https://cdn2.thecatapi.com/images/TnwHiS7nO.jpg",
//       width: 1920,
//       height: 1080,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "5 - 11", metric: "2 - 5" },
//           id: "sfol",
//           name: "Scottish Fold",
//           cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
//           vetstreet_url:
//             "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
//           temperament:
//             "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
//           origin: "United Kingdom",
//           country_codes: "GB",
//           country_code: "GB",
//           description:
//             'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
//           life_span: "11 - 14",
//           indoor: 0,
//           alt_names: "Scot Fold",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 3,
//           grooming: 1,
//           health_issues: 4,
//           intelligence: 3,
//           shedding_level: 3,
//           social_needs: 3,
//           stranger_friendly: 3,
//           vocalisation: 1,
//           experimental: 0,
//           hairless: 0,
//           natural: 0,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
//           hypoallergenic: 0,
//           reference_image_id: "o9t0LDcsa",
//         },
//       ],
//       id: "JYLVJkyq_",
//       url: "https://cdn2.thecatapi.com/images/JYLVJkyq_.jpg",
//       width: 4330,
//       height: 2436,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "5 - 11", metric: "2 - 5" },
//           id: "sfol",
//           name: "Scottish Fold",
//           cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
//           vetstreet_url:
//             "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
//           temperament:
//             "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
//           origin: "United Kingdom",
//           country_codes: "GB",
//           country_code: "GB",
//           description:
//             'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
//           life_span: "11 - 14",
//           indoor: 0,
//           alt_names: "Scot Fold",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 3,
//           grooming: 1,
//           health_issues: 4,
//           intelligence: 3,
//           shedding_level: 3,
//           social_needs: 3,
//           stranger_friendly: 3,
//           vocalisation: 1,
//           experimental: 0,
//           hairless: 0,
//           natural: 0,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
//           hypoallergenic: 0,
//           reference_image_id: "o9t0LDcsa",
//         },
//       ],
//       id: "Tbc8_VStM",
//       url: "https://cdn2.thecatapi.com/images/Tbc8_VStM.jpg",
//       width: 1500,
//       height: 996,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "5 - 11", metric: "2 - 5" },
//           id: "sfol",
//           name: "Scottish Fold",
//           cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
//           vetstreet_url:
//             "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
//           temperament:
//             "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
//           origin: "United Kingdom",
//           country_codes: "GB",
//           country_code: "GB",
//           description:
//             'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
//           life_span: "11 - 14",
//           indoor: 0,
//           alt_names: "Scot Fold",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 3,
//           grooming: 1,
//           health_issues: 4,
//           intelligence: 3,
//           shedding_level: 3,
//           social_needs: 3,
//           stranger_friendly: 3,
//           vocalisation: 1,
//           experimental: 0,
//           hairless: 0,
//           natural: 0,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
//           hypoallergenic: 0,
//           reference_image_id: "o9t0LDcsa",
//         },
//       ],
//       id: "o9t0LDcsa",
//       url: "https://cdn2.thecatapi.com/images/o9t0LDcsa.jpg",
//       width: 1920,
//       height: 1440,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "5 - 11", metric: "2 - 5" },
//           id: "sfol",
//           name: "Scottish Fold",
//           cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
//           vetstreet_url:
//             "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
//           temperament:
//             "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
//           origin: "United Kingdom",
//           country_codes: "GB",
//           country_code: "GB",
//           description:
//             'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
//           life_span: "11 - 14",
//           indoor: 0,
//           alt_names: "Scot Fold",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 3,
//           grooming: 1,
//           health_issues: 4,
//           intelligence: 3,
//           shedding_level: 3,
//           social_needs: 3,
//           stranger_friendly: 3,
//           vocalisation: 1,
//           experimental: 0,
//           hairless: 0,
//           natural: 0,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
//           hypoallergenic: 0,
//           reference_image_id: "o9t0LDcsa",
//         },
//       ],
//       id: "5txKBK89Y",
//       url: "https://cdn2.thecatapi.com/images/5txKBK89Y.jpg",
//       width: 3912,
//       height: 2602,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "5 - 10", metric: "2 - 5" },
//           id: "tang",
//           name: "Turkish Angora",
//           cfa_url: "http://cfa.org/Breeds/BreedsSthruT/TurkishAngora.aspx",
//           vetstreet_url: "http://www.vetstreet.com/cats/turkish-angora",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/turkish-angora",
//           temperament:
//             "Affectionate, Agile, Clever, Gentle, Intelligent, Playful, Social",
//           origin: "Turkey",
//           country_codes: "TR",
//           country_code: "TR",
//           description:
//             "This is a smart and intelligent cat which bonds well with humans. With its affectionate and playful personality the Angora is a top choice for families. The Angora gets along great with other pets in the home, but it will make clear who is in charge, and who the house belongs to",
//           life_span: "15 - 18",
//           indoor: 0,
//           alt_names: "Ankara",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 5,
//           grooming: 2,
//           health_issues: 2,
//           intelligence: 5,
//           shedding_level: 2,
//           social_needs: 5,
//           stranger_friendly: 5,
//           vocalisation: 3,
//           experimental: 0,
//           hairless: 0,
//           natural: 1,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Turkish_Angora",
//           hypoallergenic: 0,
//           reference_image_id: "7CGV6WVXq",
//         },
//       ],
//       id: "41Fe8q9vU",
//       url: "https://cdn2.thecatapi.com/images/41Fe8q9vU.jpg",
//       width: 1080,
//       height: 1080,
//     },
//     {
//       breeds: [
//         {
//           weight: { imperial: "5 - 10", metric: "2 - 5" },
//           id: "tang",
//           name: "Turkish Angora",
//           cfa_url: "http://cfa.org/Breeds/BreedsSthruT/TurkishAngora.aspx",
//           vetstreet_url: "http://www.vetstreet.com/cats/turkish-angora",
//           vcahospitals_url:
//             "https://vcahospitals.com/know-your-pet/cat-breeds/turkish-angora",
//           temperament:
//             "Affectionate, Agile, Clever, Gentle, Intelligent, Playful, Social",
//           origin: "Turkey",
//           country_codes: "TR",
//           country_code: "TR",
//           description:
//             "This is a smart and intelligent cat which bonds well with humans. With its affectionate and playful personality the Angora is a top choice for families. The Angora gets along great with other pets in the home, but it will make clear who is in charge, and who the house belongs to",
//           life_span: "15 - 18",
//           indoor: 0,
//           alt_names: "Ankara",
//           adaptability: 5,
//           affection_level: 5,
//           child_friendly: 4,
//           dog_friendly: 5,
//           energy_level: 5,
//           grooming: 2,
//           health_issues: 2,
//           intelligence: 5,
//           shedding_level: 2,
//           social_needs: 5,
//           stranger_friendly: 5,
//           vocalisation: 3,
//           experimental: 0,
//           hairless: 0,
//           natural: 1,
//           rare: 0,
//           rex: 0,
//           suppressed_tail: 0,
//           short_legs: 0,
//           wikipedia_url: "https://en.wikipedia.org/wiki/Turkish_Angora",
//           hypoallergenic: 0,
//           reference_image_id: "7CGV6WVXq",
//         },
//       ],
//       id: "58mi0uCwO",
//       url: "https://cdn2.thecatapi.com/images/58mi0uCwO.jpg",
//       width: 1600,
//       height: 1200,
//     },
//   ];

//   async function fetchData() {
//     // try {
//     //   const response = await fetch(url);
//     //   const data = await response.json();
//     //   cats.push(...data);
//     // } catch (err) {
//     //   console.log(err.message);
//     // }
//   }

//   function getCatsByTheLargestLifeSpan() {
//     let highestAge = 0;
//     let searchIndex;

//     cats.forEach((cat, index) => {
//       let catObject = cat.breeds[0];
//       let lifeSpan = catObject["life_span"];

//       let age = Number(lifeSpan.split("_")[1]);
//       searchIndex = index;

//       if (age > highestAge) {
//         highestAge = age;
//       }
//     });

//     const catsAsArray = [cats[searchIndex]];

//     return catsAsArray;
//   }

//   function getAllCats(requestedAction) {
//     console.log(requestedAction)
//     requestedAction();
//     return cats;
//   }

//   return { fetchData, getAllCats, getCatsByTheLargestLifeSpan };
// }

class catContext {
  constructor() {
    this.cats = [
      {
        breeds: [
          {
            weight: { imperial: "8 - 18", metric: "4 - 8" },
            id: "bslo",
            name: "British Longhair",
            temperament:
              "Affectionate, Easy Going, Independent, Intelligent, Loyal, Social",
            origin: "United Kingdom",
            country_codes: "GB",
            country_code: "GB",
            description:
              "The British Longhair is a very laid-back relaxed cat, often perceived to be very independent although they will enjoy the company of an equally relaxed and likeminded cat. They are an affectionate breed, but very much on their own terms and tend to prefer to choose to come and sit with their owners rather than being picked up.",
            life_span: "12 - 14",
            indoor: 0,
            alt_names: "",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 4,
            grooming: 5,
            health_issues: 1,
            intelligence: 5,
            shedding_level: 1,
            social_needs: 3,
            stranger_friendly: 4,
            vocalisation: 1,
            experimental: 0,
            hairless: 0,
            natural: 0,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/British_Longhair",
            hypoallergenic: 0,
            reference_image_id: "7isAO4Cav",
          },
        ],
        id: "JWOrjbhum",
        url: "https://cdn2.thecatapi.com/images/JWOrjbhum.jpg",
        width: 768,
        height: 1024,
      },
      {
        breeds: [
          {
            weight: { imperial: "9 - 14", metric: "4 - 6" },
            id: "pers",
            name: "Persian",
            cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Persian.aspx",
            vetstreet_url: "http://www.vetstreet.com/cats/persian",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/persian",
            temperament: "Affectionate, loyal, Sedate, Quiet",
            origin: "Iran (Persia)",
            country_codes: "IR",
            country_code: "IR",
            description:
              "Persians are sweet, gentle cats that can be playful or quiet and laid-back. Great with families and children, they absolutely love to lounge around the house. While they don’t mind a full house or active kids, they’ll usually hide when they need some alone time.",
            life_span: "14 - 15",
            indoor: 0,
            lap: 1,
            alt_names: "Longhair, Persian Longhair, Shiraz, Shirazi",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 2,
            dog_friendly: 2,
            energy_level: 1,
            grooming: 5,
            health_issues: 3,
            intelligence: 3,
            shedding_level: 4,
            social_needs: 4,
            stranger_friendly: 2,
            vocalisation: 1,
            experimental: 0,
            hairless: 0,
            natural: 1,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Persian_(cat)",
            hypoallergenic: 0,
            reference_image_id: "-Zfz5z2jK",
          },
        ],
        id: "tSbM4vHB_",
        url: "https://cdn2.thecatapi.com/images/tSbM4vHB_.png",
        width: 4096,
        height: 2304,
      },
      {
        breeds: [
          {
            weight: { imperial: "12 - 20", metric: "5 - 9" },
            id: "ragd",
            name: "Ragdoll",
            cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Ragdoll.aspx",
            vetstreet_url: "http://www.vetstreet.com/cats/ragdoll",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/ragdoll",
            temperament: "Affectionate, Friendly, Gentle, Quiet, Easygoing",
            origin: "United States",
            country_codes: "US",
            country_code: "US",
            description:
              "Ragdolls love their people, greeting them at the door, following them around the house, and leaping into a lap or snuggling in bed whenever given the chance. They are the epitome of a lap cat, enjoy being carried and collapsing into the arms of anyone who holds them.",
            life_span: "12 - 17",
            indoor: 0,
            lap: 1,
            alt_names: "Rag doll",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 3,
            grooming: 2,
            health_issues: 3,
            intelligence: 3,
            shedding_level: 3,
            social_needs: 5,
            stranger_friendly: 3,
            vocalisation: 1,
            experimental: 0,
            hairless: 0,
            natural: 0,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Ragdoll",
            hypoallergenic: 0,
            reference_image_id: "oGefY4YoG",
          },
        ],
        id: "UYLI_E-SZ",
        url: "https://cdn2.thecatapi.com/images/UYLI_E-SZ.jpg",
        width: 750,
        height: 500,
      },
      {
        breeds: [
          {
            weight: { imperial: "12 - 20", metric: "5 - 9" },
            id: "ragd",
            name: "Ragdoll",
            cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Ragdoll.aspx",
            vetstreet_url: "http://www.vetstreet.com/cats/ragdoll",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/ragdoll",
            temperament: "Affectionate, Friendly, Gentle, Quiet, Easygoing",
            origin: "United States",
            country_codes: "US",
            country_code: "US",
            description:
              "Ragdolls love their people, greeting them at the door, following them around the house, and leaping into a lap or snuggling in bed whenever given the chance. They are the epitome of a lap cat, enjoy being carried and collapsing into the arms of anyone who holds them.",
            life_span: "12 - 17",
            indoor: 0,
            lap: 1,
            alt_names: "Rag doll",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 3,
            grooming: 2,
            health_issues: 3,
            intelligence: 3,
            shedding_level: 3,
            social_needs: 5,
            stranger_friendly: 3,
            vocalisation: 1,
            experimental: 0,
            hairless: 0,
            natural: 0,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Ragdoll",
            hypoallergenic: 0,
            reference_image_id: "oGefY4YoG",
          },
        ],
        id: "TnwHiS7nO",
        url: "https://cdn2.thecatapi.com/images/TnwHiS7nO.jpg",
        width: 1920,
        height: 1080,
      },
      {
        breeds: [
          {
            weight: { imperial: "5 - 11", metric: "2 - 5" },
            id: "sfol",
            name: "Scottish Fold",
            cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
            vetstreet_url:
              "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
            temperament:
              "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
            origin: "United Kingdom",
            country_codes: "GB",
            country_code: "GB",
            description:
              'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
            life_span: "11 - 14",
            indoor: 0,
            alt_names: "Scot Fold",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 3,
            grooming: 1,
            health_issues: 4,
            intelligence: 3,
            shedding_level: 3,
            social_needs: 3,
            stranger_friendly: 3,
            vocalisation: 1,
            experimental: 0,
            hairless: 0,
            natural: 0,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
            hypoallergenic: 0,
            reference_image_id: "o9t0LDcsa",
          },
        ],
        id: "JYLVJkyq_",
        url: "https://cdn2.thecatapi.com/images/JYLVJkyq_.jpg",
        width: 4330,
        height: 2436,
      },
      {
        breeds: [
          {
            weight: { imperial: "5 - 11", metric: "2 - 5" },
            id: "sfol",
            name: "Scottish Fold",
            cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
            vetstreet_url:
              "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
            temperament:
              "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
            origin: "United Kingdom",
            country_codes: "GB",
            country_code: "GB",
            description:
              'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
            life_span: "11 - 14",
            indoor: 0,
            alt_names: "Scot Fold",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 3,
            grooming: 1,
            health_issues: 4,
            intelligence: 3,
            shedding_level: 3,
            social_needs: 3,
            stranger_friendly: 3,
            vocalisation: 1,
            experimental: 0,
            hairless: 0,
            natural: 0,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
            hypoallergenic: 0,
            reference_image_id: "o9t0LDcsa",
          },
        ],
        id: "Tbc8_VStM",
        url: "https://cdn2.thecatapi.com/images/Tbc8_VStM.jpg",
        width: 1500,
        height: 996,
      },
      {
        breeds: [
          {
            weight: { imperial: "5 - 11", metric: "2 - 5" },
            id: "sfol",
            name: "Scottish Fold",
            cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
            vetstreet_url:
              "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
            temperament:
              "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
            origin: "United Kingdom",
            country_codes: "GB",
            country_code: "GB",
            description:
              'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
            life_span: "11 - 14",
            indoor: 0,
            alt_names: "Scot Fold",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 3,
            grooming: 1,
            health_issues: 4,
            intelligence: 3,
            shedding_level: 3,
            social_needs: 3,
            stranger_friendly: 3,
            vocalisation: 1,
            experimental: 0,
            hairless: 0,
            natural: 0,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
            hypoallergenic: 0,
            reference_image_id: "o9t0LDcsa",
          },
        ],
        id: "o9t0LDcsa",
        url: "https://cdn2.thecatapi.com/images/o9t0LDcsa.jpg",
        width: 1920,
        height: 1440,
      },
      {
        breeds: [
          {
            weight: { imperial: "5 - 11", metric: "2 - 5" },
            id: "sfol",
            name: "Scottish Fold",
            cfa_url: "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
            vetstreet_url:
              "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
            temperament:
              "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
            origin: "United Kingdom",
            country_codes: "GB",
            country_code: "GB",
            description:
              'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
            life_span: "11 - 14",
            indoor: 0,
            alt_names: "Scot Fold",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 3,
            grooming: 1,
            health_issues: 4,
            intelligence: 3,
            shedding_level: 3,
            social_needs: 3,
            stranger_friendly: 3,
            vocalisation: 1,
            experimental: 0,
            hairless: 0,
            natural: 0,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Scottish_Fold",
            hypoallergenic: 0,
            reference_image_id: "o9t0LDcsa",
          },
        ],
        id: "5txKBK89Y",
        url: "https://cdn2.thecatapi.com/images/5txKBK89Y.jpg",
        width: 3912,
        height: 2602,
      },
      {
        breeds: [
          {
            weight: { imperial: "5 - 10", metric: "2 - 5" },
            id: "tang",
            name: "Turkish Angora",
            cfa_url: "http://cfa.org/Breeds/BreedsSthruT/TurkishAngora.aspx",
            vetstreet_url: "http://www.vetstreet.com/cats/turkish-angora",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/turkish-angora",
            temperament:
              "Affectionate, Agile, Clever, Gentle, Intelligent, Playful, Social",
            origin: "Turkey",
            country_codes: "TR",
            country_code: "TR",
            description:
              "This is a smart and intelligent cat which bonds well with humans. With its affectionate and playful personality the Angora is a top choice for families. The Angora gets along great with other pets in the home, but it will make clear who is in charge, and who the house belongs to",
            life_span: "15 - 18",
            indoor: 0,
            alt_names: "Ankara",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 5,
            grooming: 2,
            health_issues: 2,
            intelligence: 5,
            shedding_level: 2,
            social_needs: 5,
            stranger_friendly: 5,
            vocalisation: 3,
            experimental: 0,
            hairless: 0,
            natural: 1,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Turkish_Angora",
            hypoallergenic: 0,
            reference_image_id: "7CGV6WVXq",
          },
        ],
        id: "41Fe8q9vU",
        url: "https://cdn2.thecatapi.com/images/41Fe8q9vU.jpg",
        width: 1080,
        height: 1080,
      },
      {
        breeds: [
          {
            weight: { imperial: "5 - 10", metric: "2 - 5" },
            id: "tang",
            name: "Turkish Angora",
            cfa_url: "http://cfa.org/Breeds/BreedsSthruT/TurkishAngora.aspx",
            vetstreet_url: "http://www.vetstreet.com/cats/turkish-angora",
            vcahospitals_url:
              "https://vcahospitals.com/know-your-pet/cat-breeds/turkish-angora",
            temperament:
              "Affectionate, Agile, Clever, Gentle, Intelligent, Playful, Social",
            origin: "Turkey",
            country_codes: "TR",
            country_code: "TR",
            description:
              "This is a smart and intelligent cat which bonds well with humans. With its affectionate and playful personality the Angora is a top choice for families. The Angora gets along great with other pets in the home, but it will make clear who is in charge, and who the house belongs to",
            life_span: "15 - 18",
            indoor: 0,
            alt_names: "Ankara",
            adaptability: 5,
            affection_level: 5,
            child_friendly: 4,
            dog_friendly: 5,
            energy_level: 5,
            grooming: 2,
            health_issues: 2,
            intelligence: 5,
            shedding_level: 2,
            social_needs: 5,
            stranger_friendly: 5,
            vocalisation: 3,
            experimental: 0,
            hairless: 0,
            natural: 1,
            rare: 0,
            rex: 0,
            suppressed_tail: 0,
            short_legs: 0,
            wikipedia_url: "https://en.wikipedia.org/wiki/Turkish_Angora",
            hypoallergenic: 0,
            reference_image_id: "7CGV6WVXq",
          },
        ],
        id: "58mi0uCwO",
        url: "https://cdn2.thecatapi.com/images/58mi0uCwO.jpg",
        width: 1600,
        height: 1200,
      },
    ];
  }

  fetchData() {
    // try {
    //   const response = await fetch(url);
    //   const data = await response.json();
    //   cats.push(...data);
    // } catch (err) {
    //   console.log(err.message);
    // }
  }

  getCatsByTheLargestLifeSpan () {
    let highestAge = 0;
    let searchIndex;
     console.log(this.cats)

    this.cats.forEach((cat, index) => {
      let catObject = cat.breeds[0];
      let lifeSpan = catObject["life_span"];

      let age = Number(lifeSpan.split("_")[1]);
      searchIndex = index;

      if (age > highestAge) {
        highestAge = age;
      }
    });

    const catsAsArray = [this.cats[searchIndex]];

    return catsAsArray;
  }

  getAllCats() {
    fetchData();

    return this.cats;
  }
}

export default catContext;
