# Generated by Django 5.1.4 on 2024-12-06 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_credential_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentDetails',
            fields=[
                ('card_holder', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 36 characters'}, max_length=36, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='This field must be at least 5 characters long'), django.core.validators.RegexValidator(message='Card Holder Name can only contain letters, spaces, hyphens, apostrophes, and periods, and must start and end with a letter', regex="(^[A-Za-z]{1,}[A-Za-z\\s\\-'\\.]*[A-Za-z]{1,}$)")])),
                ('card_number', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 16 characters'}, max_length=16, validators=[django.core.validators.MinLengthValidator(limit_value=16, message='This field must be at least 16 characters long'), django.core.validators.RegexValidator(message='The Card Number can only contain digits', regex='^[0-9]+$')])),
                ('expiry_month', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('expiry_year', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035')], max_length=4)),
                ('cvv_code', models.CharField(error_messages={'blank': 'This field is required', 'max_length': 'This field must not exceed 3 characters'}, max_length=3, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='This field must be at least 3 characters long'), django.core.validators.RegexValidator(message='The CVV Code can only contain digits', regex='^[0-9]+$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_details', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
