# Generated by Django 5.1.3 on 2024-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='delivery_method',
            field=models.CharField(choices=[('SP', 'Store Pickup'), ('EH', 'Express Home Delivery'), ('RH', 'Regular Home Delivery')], default='SP', max_length=2),
            preserve_default=False,
        ),
    ]
