# Generated by Django 5.0 on 2023-12-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='sold_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
