# Generated by Django 5.0 on 2024-01-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='price',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='sold_out',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='updated_at',
        ),
    ]
