# Generated by Django 5.0 on 2024-01-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=18),
        ),
    ]
