# Generated by Django 4.2 on 2024-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonetype',
            name='title',
            field=models.CharField(choices=[('BS', 'Spinel'), ('DI', 'Diamond'), ('EM', 'Emerald'), ('RU', 'Ruby'), ('SA', 'Sapphire')], max_length=2),
        ),
    ]
