# Generated by Django 4.2 on 2024-01-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_alter_stonetype_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelry',
            options={'verbose_name_plural': 'Jewelries'},
        ),
    ]
