# Generated by Django 4.2 on 2024-01-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0003_alter_jewelry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('B', 'Bracelet'), ('E', 'Earring'), ('N', 'Necklace'), ('R', 'Ring')], max_length=1),
        ),
    ]
