# Generated by Django 4.2 on 2024-02-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('size', models.CharField(max_length=10)),
                ('order_completed', models.BooleanField(default=False)),
                ('session_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry.jewelry')),
            ],
            options={
                'unique_together': {('session_key', 'jewelry')},
            },
        ),
    ]
