# Generated by Django 4.2 on 2024-01-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JewelryLike',
        ),
    ]
