# Generated by Django 5.0 on 2024-01-05 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_image_jewelrylike_jewelry'),
        ('jewelry', '0002_alter_jewelry_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelrylike',
            name='jewelry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jewelry.jewelry'),
        ),
        migrations.AlterUniqueTogether(
            name='jewelrylike',
            unique_together={('jewelry', 'user')},
        ),
    ]
