# Generated by Django 5.0 on 2024-01-09 12:53

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import e_commerce_website.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), e_commerce_website.core.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), e_commerce_website.core.validators.validate_only_letters])),
                ('phone_number', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(10), e_commerce_website.core.validators.validate_only_digits])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField()),
                ('delivery_address', models.CharField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
