# Generated by Django 4.2 on 2024-02-05 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import e_commerce_website.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('first_name', models.CharField(error_messages={'max_length': 'Ensure your First Name does not exceed 30 characters.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Ensure your First Name consists of at least 2 characters.'), e_commerce_website.profiles.validators.OnlyLettersValidator(error_message='Ensure your First Name contains only letters.')])),
                ('last_name', models.CharField(error_messages={'max_length': 'Ensure your Last Name does not exceed 30 characters.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Ensure your Last Name consists of at least 2 characters.'), e_commerce_website.profiles.validators.OnlyLettersValidator(error_message='Ensure your Last Name contains only letters.')])),
                ('phone_number', models.CharField(error_messages={'max_length': 'Ensure your Phone Number does not exceed 30 digits.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(10, message='Ensure your Phone Number consist of at least 10 digits.'), e_commerce_website.profiles.validators.OnlyDigitsValidator(error_message='Ensure your Phone Number contains only digits.')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(error_messages={'max_length': 'Ensure your City does not exceed 30 characters.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Ensure your City consist of at least 2 characters.'), e_commerce_website.profiles.validators.OnlyLettersValidator(error_message='Ensure your Your City contains only letters.')])),
                ('delivery_address', models.CharField(error_messages={'max_length': 'Ensure your Address does not exceed 30 characters.'}, max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Ensure your Address consist of at least 2 characters.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
