# Generated by Django 5.1.3 on 2024-11-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BraceletPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(choices=[(34000.0, 34000.0), (35000.0, 35000.0), (36000.0, 36000.0)], decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='BraceletSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(choices=[(15.02, 15.02), (17.08, 17.08), (19.03, 19.03)], decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('P', 'Pink'), ('B', 'Blue'), ('W', 'White')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EarringPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(choices=[(43000.0, 43000.0), (44000.0, 44000.0), (45000.0, 45000.0)], decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='EarringSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(choices=[(4.05, 4.05), (4.98, 4.98), (5.86, 5.86)], decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='NecklacePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(choices=[(55000.0, 55000.0), (56000.0, 56000.0), (57000.0, 57000.0)], decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='NecklaceSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(choices=[(40.64, 40.64), (43.18, 43.18), (45.72, 45.72)], decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(choices=[(23000.0, 23000.0), (24000.0, 24000.0), (25000.0, 25000.0)], decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='RingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.DecimalField(choices=[(4.07, 4.07), (4.09, 4.09), (5.05, 5.05)], decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracelet_price', to='product.braceletprice')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracelet_size', to='product.braceletsize')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('quantity', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earring_price', to='product.earringprice')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earring_size', to='product.earringsize')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('quantity', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necklace_price', to='product.necklaceprice')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necklace_size', to='product.necklacesize')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('quantity', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ring_price', to='product.ringprice')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ring_size', to='product.ringsize')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
