# Generated by Django 5.1.3 on 2024-11-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_image_url',
            field=models.URLField(default='https://link.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='second_image_url',
            field=models.URLField(default='https://link.com'),
            preserve_default=False,
        ),
    ]
