STYLE_MAPPER = {
    1: 'id_style_choices_0',
    2: 'id_style_choices_1',
    3: 'id_style_choices_2',
    4: 'id_style_choices_3',
    5: 'id_style_choices_4',
    6: 'id_style_choices_5',
    7: 'id_style_choices_6',
    8: 'id_style_choices_7',
    9: 'id_style_choices_8',
    10: 'id_style_choices_9',
    11: 'id_style_choices_10',
    12: 'id_style_choices_11',
    13: 'id_style_choices_12',
    14: 'id_style_choices_13',
    15: 'id_style_choices_14',
}

METAL_MAPPER = {
    1: 'id_metal_choices_0',
    2: 'id_metal_choices_1',
    3: 'id_metal_choices_2',
    4: 'id_metal_choices_3',
}

STONE_TYPE_MAPPER = {
   1: 'id_stone_type_choices_0',
   2: 'id_stone_type_choices_1',
   3: 'id_stone_type_choices_2',
   4: 'id_stone_type_choices_3',
   5: 'id_stone_type_choices_4',
   6: 'id_stone_type_choices_5',
   7: 'id_stone_type_choices_6',
   8: 'id_stone_type_choices_7',
   9: 'id_stone_type_choices_8',
   10: 'id_stone_type_choices_9',
   11: 'id_stone_type_choices_10',
   12: 'id_stone_type_choices_11',
   13: 'id_stone_type_choices_12',
   14: 'id_stone_type_choices_13',
   15: 'id_stone_type_choices_14',
   16: 'id_stone_type_choices_15',
   17: 'id_stone_type_choices_16',
   18: 'id_stone_type_choices_17',
   19: 'id_stone_type_choices_18',
   20: 'id_stone_type_choices_19',
   21: 'id_stone_type_choices_20',
   22: 'id_stone_type_choices_21',
   23: 'id_stone_type_choices_22',
   24: 'id_stone_type_choices_23',
   25: 'id_stone_type_choices_24',
   26: 'id_stone_type_choices_25',
   27: 'id_stone_type_choices_26',
   28: 'id_stone_type_choices_27',
}
