# Generated by Django 5.0.4 on 2024-11-21 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveBigIntegerField(default=19, validators=[django.core.validators.MinValueValidator(18, message='Age must be greater than or equal to 18')]),
            preserve_default=False,
        ),
    ]
