# Generated by Django 5.2 on 2025-04-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_and_time_of_publication']},
        ),
    ]
