# Generated by Django 5.0.4 on 2024-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='website_url',
            field=models.URLField(default='https://softuni.bg/trainings/4253/python-orm-october-2023#lesson-59969', error_messages={'invalid': 'Enter a valid URL'}),
            preserve_default=False,
        ),
    ]
