# Generated by Django 5.2 on 2025-04-22 08:21

import django.core.validators
import myMusicApp.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), myMusicApp.profiles.validators.AlphanumericUnderscoreValidator()]),
        ),
    ]
