# Generated by Django 5.2 on 2025-04-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('languages', models.CharField(choices=[('Py', 'Python'), ('JS', 'Javascript'), ('C', 'C'), ('OT', 'Other')], default='OT', max_length=20)),
            ],
        ),
    ]
