# Generated by Django 5.0.4 on 2024-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='beatris@gmail.com', error_messages={'invalid': 'Enter a valid email address'}, max_length=254),
            preserve_default=False,
        ),
    ]
