# Generated by Django 5.2 on 2025-04-26 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'unique': 'Oops! That title is already taken.How about something fresh and fun?'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
