# Generated by Django 5.2 on 2025-04-13 09:57

from datetime import timedelta
from main_app.choices import StatusChoices

from django.db import migrations


class Migration(migrations.Migration):

    def update_delivery_and_warranty(apps, schema_editor):
        OrderModel = apps.get_model('main_app', 'Order')

        for order in OrderModel.objects.all():
            if order.status == StatusChoices.PENDING:
                order.delivery = order.order_date + timedelta(days=3)
                order.save()

            elif order.status == StatusChoices.COMPLETED:
                order.warranty = '24 months'
                order.save()

            elif order.status == StatusChoices.CANCELLED:
                order.delete()

    dependencies = [
        ('main_app', '0008_order_person'),
    ]

    operations = [
        migrations.RunPython(code=update_delivery_and_warranty)
    ]
